### Sourcing external config files ###
$configs = $HOME/.config/hypr/configs # Default Configs directory path

source=$configs/ENVariables.conf
source=$configs/Keybinds.conf
# source=$configs/Laptops.conf
source=$configs/Startup_Apps.conf
source=$configs/SystemSettings.conf
source=$configs/UserDecorations.conf
source=$configs/WindowRules.conf
source=$configs/monitors.conf

input {
	numlock_by_default = true
}

exec-once = hyprpm reload -n

general {
    layout = hy3
}

plugin {
    hy3 {
        no_gaps_when_only = 1
        tab_first_window = false
        node_collapse_policy = 2

        autotile {
            enable = true
        }
    }
}

