# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F0DBEB
background         #2C242E
cursor             #B7A1B7

active_tab_foreground     #2C242E
active_tab_background     #F0DBEB
inactive_tab_foreground   #F0DBEB
inactive_tab_background   #2C242E

active_border_color   #F0DBEB
inactive_border_color #2C242E
bell_border_color     #A07395

color0      #534F53
color1		#A07395
color2		#A07395
color3		#A07395
color4		#6D4A61
color5		#5E4D62
color6		#5E4D62
color7		#E2C4DB
color8		#9E8999
color9		#D599C7
color10		#D599C7
color11		#D599C7
color12		#926282
color13		#7E6683
color14		#7E6683
color15		#E2C4DB
