# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #AEABB3
background         #08050E
cursor             #AC6F8F

active_tab_foreground     #08050E
active_tab_background     #AEABB3
inactive_tab_foreground   #AEABB3
inactive_tab_background   #08050E

active_border_color   #AEABB3
inactive_border_color #08050E
bell_border_color     #120A1D

color0      #463839
color1		#120A1D
color2		#120A1D
color3		#1C1123
color4		#5B3B49
color5		#7F2750
color6		#8F5D68
color7		#837E8B
color8		#5C5861
color9		#180E27
color10		#180E27
color11		#26172F
color12		#794E61
color13		#AA346B
color14		#BE7C8B
color15		#837E8B
