# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ADAEAE
background         #070808
cursor             #A6A6A0

active_tab_foreground     #070808
active_tab_background     #ADAEAE
inactive_tab_foreground   #ADAEAE
inactive_tab_background   #070808

active_border_color   #ADAEAE
inactive_border_color #070808
bell_border_color     #101112

color0      #51504D
color1		#101112
color2		#1A1B1B
color3		#4E4E49
color4		#67675B
color5		#77766D
color6		#B5B3A4
color7		#828383
color8		#5B5B5C
color9		#151718
color10		#232524
color11		#676861
color12		#898979
color13		#9E9E92
color14		#F1EFDB
color15		#828383
