[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" }
]
obsidian = [
    { run = 'obsidian "$@"', orphan = true, for = "unix" }
]
office = [
    { run = 'libreoffice "$@"', orphan = true, for = "unix" }
]
# Add a generic open for everything else
default = [
    { run = 'xdg-open "$@"', orphan = true, for = "unix" }
]
