# Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

# Monitors
monitor=,preferred,auto,1

# High Refresh Rate
monitor=,highrr,auto,1

# High Resolution
monitor=,highres,auto,1

#Eric's changes
# Sansui 24" on HDMI-A-2 (iGPU): left monitor

# monitor=HDMI-A-7, 1920x1080@180, 0x0, 1

# KTC H34S18S ultrawide on DP-2: right monitor, native res, 1.25 scale, 10-bit color
monitor=DP-2, 3440x1440@165, 0x0, 1.25, bitdepth, 10

