# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Decoration Settings

# Hyprland Wiki Links
# Animation - https://wiki.hyprland.org/Configuring/Animations/
# Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

general {
  border_size = 1
  gaps_in = 3
  gaps_out = 3

  col.active_border = rgba(cba6f7ee) 
  col.inactive_border = rgba(45475aaa)
}

decoration {
  rounding = 0
         
  active_opacity = 1.0
  inactive_opacity = 1.0
  fullscreen_opacity = 1.0
  dim_inactive = false 

  shadow {
    enabled = false 
    range = 3
    render_power = 3

    color =  rgba(11111bcc)
    color_inactive = rgba(45475a66)
  }


  blur {
    enabled = true	
    size = 6
    passes = 2
    ignore_opacity = true
    new_optimizations = true
    special = true
    popups = true
  }
}

animations {
  enabled = false
}

group {
  col.border_active = rgba(cdd6f4ee)

	groupbar {
		col.active = rgba(1e1e2eee)
  }
}
