# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010A14)
$foreground = rgb(BBD5F1)
$color0 = rgb(404249)
$color1 = rgb(2E65A1)
$color2 = rgb(732D42)
$color3 = rgb(26406D)
$color4 = rgb(422338)
$color5 = rgb(09162D)
$color6 = rgb(02152C)
$color7 = rgb(96BAE3)
$color8 = rgb(69829F)
$color9 = rgb(3D86D7)
$color10 = rgb(993C58)
$color11 = rgb(335591)
$color12 = rgb(572E4B)
$color13 = rgb(0C1E3C)
$color14 = rgb(031C3A)
$color15 = rgb(96BAE3)
